require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/**/*
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - spec/**/*

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/tasks/**/*
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - app/models/*

Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
