language: ruby
sudo: false

notifications:
  email: false

cache:
  bundler: true

services:
  - postgresql

bundler_args: --jobs 3 --retry 3

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup

env:
  global:
    - "RAILS_ENV=test"

matrix:
  fast_finish: true

jobs:
  fast_finish: true
  include:
    - stage: Static Analysis
      env:
        - "RUBOCOP=true"
      before_script: /bin/true
      script:
        - bundle exec rubocop

    - stage: Static Analysis
      script:
        - bundle exec rake spec
