version: "2"

volumes:
  db:
    external: false
  storage:
    external: false

services:
  db:
    environment:
      POSTGRES_DB: skyOS_production
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    image: postgres:10-alpine
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    environment:
      POSTGRES_DB: skyOS_production
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: db
      RAILS_HOSTNAME: demo.lonestar-virtual.org
      RAILS_LOG_TO_STDOUT: 1
      # RAILS_MASTER_KEY: blahblahblah
      RAILS_SERVE_STATIC_FILES: 1
      SKY_OS_REPLY_TO: staff@lonestar-virtual.org
    volumes:
      - storage:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
