name: Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build . --file Dockerfile

  publish:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: 'Publish to GitHub Registry (tag: experimental)'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lonestarvirtual/skyos/skyos
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: experimental

      - name: 'Publish Docker Hub (tag: experimental)'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lonestarvirtual/skyos
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: experimental
