name: Publish to Registry

#on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release version
        id: get_version
#        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        run: echo ::set-env name=RELEASE_VERSION::0.0

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lonestarvirtual/skyOS/skyos
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }}"
